[tool.poetry]
name = "madsproject"
version = "0.1.0"
description = ""
authors = ["[Madsjanssen] <[mjanssen@live.dk]>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
